goravel/gin

config/cors.go, cors_test.go, route_test.go
=> feat: Optimize unit tests

README.md, facades/gin.go, go.mod, go.sum, group.go, group_test.go, route.go
=> chore: Rename route

context.go, context_request.go, context_request_test.go, context_response.go, context_response_test.go, cors_test.go, go.mod, go.sum, group_test.go, response.go, route_test.go, tls_test.go, utils.go, view.go, view_test.go
=> feat: [#243] Optimize the return of controller

go.mod, go.sum, response.go, utils.go
=> feat: [#243] Optimize the return of Render

context_request.go
=> feat: remove unnecessary mutex

route.go
=> feat: disable gin default validator

context_request.go, context_request_test.go, go.mod, go.sum
Closes https://github.com/goravel/goravel/issues/378
=> fix: [#378] [Bug] InputArray returns a wrong value when requesting by form

context_request.go, context_request_test.go
=> merge v1.1.7

.github/workflows/test.yml, context_request.go, context_request_test.go, go.mod, go.sum
RelatedTo: https://github.com/goravel/goravel/issues/357
=> feat: add session helper in request context

go.mod, go.sum
=> upgrade: 1.14.3

context_response.go
Closes https://github.com/goravel/goravel/issues/455
@coderabbitai summary
=> fix: [#455] Session same_site config not working

go.mod, go.sum, route.go, route_test.go
=> feat: Optmize Shutdown

middleware_timeout.go, middleware_timeout_test.go, route.go, service_provider.go
=> fix: timeout panic

context_request.go, context_request_test.go
Closes https://github.com/goravel/goravel/issues/528
@coderabbitai summary
=> fix: [#528] GraphQL request causing errors from request body parsing

go.mod, go.sum
=> upgrade: framework v1.15.1

template.go, template_test.go, view_test.go
Closes https://github.com/goravel/goravel/issues/
=> chore: improve path concatenation for better readability

context_request.go, context_request_test.go, go.mod, go.sum
Closes https://github.com/goravel/goravel/issues/376
=> feat: [#376] ctx.Request() supports get multiple files directly

setup/setup.go
Closes https://github.com/goravel/goravel/issues/
=> chore: add route import when install

group_test.go, route_test.go
Closes https://github.com/goravel/goravel/issues/287
=> chore: [#287] optimize tests

README.md, facades/gin.go, go.mod, go.sum, service_provider.go
Closes https://github.com/goravel/goravel/issues/667
This pull request introduces several updates to the Goravel framework, focusing on simplifying package installation, updating dependencies, and enhancing the `ServiceProvider` functionality. The most important changes include revising the installation instructions in the `README.md`, updating dependency versions in `go.mod`, and adding a new `Relationship` method to the `ServiceProvider` class.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R30): Simplified installation instructions by replacing manual setup steps with a single command (`./artisan package:install`) and linking to a setup file for manual installation.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca …
=> feat: [#667] Registering service providers don't dependent order
